### ISSUE TITLE
Trying out Usearch

### ISSUE THREAD

**Issue by michaelfeil** [cohere-ai/DiskVectorIndex#1]
Great example repo! Wondering - have you tried using `usearch`. Seems to be faster in some cases over faiss.
https://github.com/unum-cloud/usearch

**Comment by nreimers** [comment]
Have used it in some cases, but wasn't able to get the same speed gains. 

Usearch is easier to start with (in my experience), but has less functionalities than faiss. Faiss has a massive selection of vector compression techniques, that allows you to build really fast, really good, and really small vector indices.

Usearch is mostly brute force and HNSW. Currently I'm mostly interested in non-HNSW indices.
